### ISSUE TITLE
CORS blocked

### ISSUE THREAD

**Issue by coolnin** [AmitXShukla/GPS-Mobile-Tracking-App#2]
the tutorial is great help but im getting this error:

Access to XMLHttpRequest at 'http://localhost:3000/signup' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

could you please help me how to solve it/

**Comment by AmitXShukla** [comment]
This error is intentional and is happening because you may not have setup your CORS correctly.

Option 1: Update Server/.env file

I do NOT recommend this approach because it lets anyone localhost access your website., So when you implement this in production, please get rid of localhost entires.
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000,http://localhost:4200

Option 2: Update Server/app.js file
Un-comment app.use AND Comment other block like

// ****** allow cross-origin requests code START ****** //

I do NOT recommend this approach because it lets anyone access your website., So when you implement this in production, please comment this and update your .env CORS with production settings.

app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
// var allowedOrigins = process.env.allowedOrigins.split(',');

// app.use(cors({
// origin: function (origin, callback) {
// allow requests with no origin
// (like mobile apps or curl requests)
// if (!origin) return callback(null, true);

// if (allowedOrigins.indexOf(origin) === -1) {
// var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
// return callback(new Error(msg), false);
// }
// return callback(null, true);
// }
// }));

// ****** allow cross-origin requests code END ****** //

**Comment by coolnin** [comment]
I did these things but the problem exists.

**Comment by AmitXShukla** [comment]
It's very hard to suggest without looking.
Can you please take screenshots, and zip all project files (except Node_modules) folder and send it to me in email amit@elishconsulting.com
or open a github repo, upload all files, send link to me
or join my FB group and send me files
https://www.facebook.com/groups/641290622965584/

**Comment by divya2426** [comment]
Hi,
Thanks for this tutorial.
I am getting  the same error.
Error =>
Access to XMLHttpRequest at 'http://localhost:3000/signup' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

How to solve this error? Can you please provide solution for this?

**Comment by AmitXShukla** [comment]
> 
> 
> Hi,
> Thanks for this tutorial.
> I am getting the same error.
> Error =>
> Access to XMLHttpRequest at 'http://localhost:3000/signup' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> How to solve this error? Can you please provide solution for this?

This error is intentional and is happening because you may not have setup your CORS correctly.

Option 1: Update Server/.env file

I do NOT recommend this approach because it lets anyone localhost access your website., So when you implement this in production, please get rid of localhost entires.
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000,http://localhost:4200

Option 2: Update Server/app.js file
Un-comment app.use AND Comment other block like

// ****** allow cross-origin requests code START ****** //

I do NOT recommend this approach because it lets anyone access your website., So when you implement this in production, please comment this and update your .env CORS with production settings.

app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
// var allowedOrigins = process.env.allowedOrigins.split(',');

// app.use(cors({
// origin: function (origin, callback) {
// allow requests with no origin
// (like mobile apps or curl requests)
// if (!origin) return callback(null, true);

// if (allowedOrigins.indexOf(origin) === -1) {
// var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
// return callback(new Error(msg), false);
// }
// return callback(null, true);
// }
// }));

// ****** allow cross-origin requests code END ****** //

**Comment by divya2426** [comment]
> > Hi,
> > Thanks for this tutorial.
> > I am getting the same error.
> > Error =>
> > Access to XMLHttpRequest at 'http://localhost:3000/signup' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> > How to solve this error? Can you please provide solution for this?
> 
> This error is intentional and is happening because you may not have setup your CORS correctly.
> 
> Option 1: Update Server/.env file
> 
> I do NOT recommend this approach because it lets anyone localhost access your website., So when you implement this in production, please get rid of localhost entires.
> allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000,http://localhost:4200
> 
> Option 2: Update Server/app.js file
> Un-comment app.use AND Comment other block like
> 
> // ****** allow cross-origin requests code START ****** //
> 
> I do NOT recommend this approach because it lets anyone access your website., So when you implement this in production, please comment this and update your .env CORS with production settings.
> 
> app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
> // var allowedOrigins = process.env.allowedOrigins.split(',');
> 
> // app.use(cors({
> // origin: function (origin, callback) {
> // allow requests with no origin
> // (like mobile apps or curl requests)
> // if (!origin) return callback(null, true);
> 
> // if (allowedOrigins.indexOf(origin) === -1) {
> // var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
> // return callback(new Error(msg), false);
> // }
> // return callback(null, true);
> // }
> // }));
> 
> // ****** allow cross-origin requests code END ****** //


Option 2 Worked.. Thanks a lot..!
